### ISSUE TITLE
Allow for sorting type imports to bottom as well

### ISSUE THREAD

**Issue by brianbolnick** [serverless-guru/prettier-import-order#2]
Love this fork. Would be awesome to allow specifying top or bottom for placement of type imports though. Ours are traditionally at the bottom of the file so having the option to customize placement would be great.

**Comment by tushar-sg** [comment]
@brianbolnick I was thinking about adding that. I will look into it this weekend.

**Comment by brianbolnick** [comment]
💪

**Comment by tusharf5** [comment]
@brianbolnick the feature is available in latest "0.3.0" release.
